dist: xenial
language: java
env:
- DC2F_ENV=production
script: "./gradlew run"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
  provider: script
  script: bash tools/gh-pages-deploy.sh
  on:
    branch: master
after_deploy:
  - ./node_modules/.bin/ts-node tools/scripts/purgecache/purgecache.ts
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in tools/travis/BLACKBOX_SECRET_KEY.txt.enc -out tools/travis/BLACKBOX_SECRET_KEY.txt -d
- gpg2 -v --import < tools/travis/BLACKBOX_SECRET_KEY.txt
- git clone https://github.com/mipmip/blackbox #&& cd blackbox && make manual-install && cd ..
- GPG=gpg2 blackbox/bin/blackbox_postdeploy
- npm install
