/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.anlage.site

import kotlin.test.*

class AppTest {
    @Test fun testAppHasAGreeting() {
        print("Hello world")
//        io.ktor.http.Url
        assertNotNull("useless Test")
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
